stages:
- inputs:
  - branch: master
    dir_name: null
    type: git
    service: sample-repo
  jobs:
  - artifact_dir: ""
    name: Build
    type: builder
  name: BUILD
  triggers:
  - type: commit
- inputs:
  - dir_name: null
    job: Build
    stage: BUILD
    type: job
  jobs:
  - deploy_permission: DEV_IN_SPACE
    deploy_type: cf
    name: Deploy
    script: |
      #!/bin/bash
      # Push app
      export CF_APP_NAME="$CF_APP"
      cf push "${CF_APP_NAME}"
      export APP_URL=http://$(cf app $CF_APP_NAME | grep -e urls: -e routes: | awk '{print $2}')
      # View logs
      #cf logs "${CF_APP_NAME}" --recent
    target:
      application: mk05-simple-toolchain-20191209142104709
      organization: some-bad-org
      # region_id: ibm:dys0:us-south
      region_id: ibm:yp:us-south
      space: some-bad-space
      # needed to add:
      api_key: some-bad-key
    type: deployer
  name: DEPLOY
  properties:
  - name: CF_APP_NAME
    type: text
    value: undefined
  - name: APP_URL
    type: text
    value: undefined
  triggers:
  - type: stage
properties: null
